"to need sth, be in need of sth","aver bisogno di qc","to need, be in need of"
"to need to do sth","aver bisogno di fare qc","to need to do sth"
"to feel like sth, want sth","aver voglia di qc","to feel like sth, want sth"
"to feel like doing sth, want to do sth","aver voglia di fare qc","to feel like doing sth, want to do sth"
"to go to smw","andare a/in qp","to go smw"
"to go to do sth","andare a fare qc","to go to do sth"
"to give sth to sb, give sb sth","dare qc a qn","to give sth to sb, give sb sth"
"to give sb sth to do","dare qc da fare a qn","to give sb sth to do"
"to say sth to sb","dire qc a qn","to say sth to sb"
"to tell sb to do sth","dire a qn di fare qc","to tell sb to do sth"
"to tell sb sth","dire a qn qc","to tell sb sth"
"to see sth","vedere qc","to see sth"
"to see sb do sth","vedere qn fare qc","to see sb do sth"
"to eat sth","mangiare qc","to eat sth"
"to talk/speak about/of sth","parlare di qc","to talk/speak about/of sth"
"to talk/speak to/with sb about/of sth","parlare a/con qn di qc","to talk/speak to/with sb about/of sth"
"to talk/speak about/of doing sth","parlare di fare qc","to talk/speak about/of doing sth"
"to take/grab sth","prendere qc","to take/grab sth"
"to read sth in smw","leggere qc su qp","to read sth in smw"
"to read about sth","leggere di qc","to read about sth"
"to love sth","amare qc","to love sth",
"to love to do sth","amare fare qc","to love to do sth"
"to drink sth","bere qc","to drink sth"
"to finish sth","finire qc","to finish sth"
"to finish doing sth","finire di fare qc","to finish doing sth"
"to understand sth","capire qc","to understand sth"
"to manage to do sth, succeed in doing sth","arrivare a fare qc","to manage to do sth, succeed in doing sth"
"to write sth to sb","scrivere qc a qn","to write sth to sb"
"to leave from/for smw","partire da/per qp","to leave form/for smw"
"to put/set sth smw","mettere qc qp","to put/set sth smw"
"to remain smw","rimanere a/in qp","to remain smw"
"to sleep smw","dormire a/in qp","to sleep smw"
"to live smw","vivere a/in qp","to live smw"
"to know sth","conoscere qc","to know sth"
"to know about/of sth","sapere di qc","to know about/of sth"
"to hear sth","sentire qc","to hear sth"
"to cook sth","cucinare qc","to cook sth"
"to study sth","studiare qc","to study sth"
"to play sth","giocare a qc","to play sth"
"to play with sth","giocare con qc","to play with sc"
"to ask sb sth","chiedere qc a qn","to ask sb sth"
"to ask about/after sb","chiedere di qn","to ask about/after sb"
"to find sth","trovare qc","to find sth"
"to believe in sb/sth","credere in qn/qc","to believe in sb/sth"
"to believe sb/sth","credere a qn/qc","to believe sb/sth"
"to open sth","aprire qc","to open sth"
"to work on sth","lavorare a qc","to work on sth"
"to think of/about sth","pensare a qc","to think of/about sth"
"to think of doing sth","pensare di fare qc","to think of doing sth"
"to run to smw","correre qp","to run to smw"
"to keep/hold sth","tenere qc","to keep/hold sth"
"to support sb/sth","tenere per qn/qc","to support sb/sth"
"to care about, attach great importance to sb/sth","tenere/tenereci a qn/qc","to care about, attach great importance to sb/sth"
"to watch sth","guardare qc","to watch sth"
"to call sb","chiamare qn","to call sb"
"to return to smw","tornare a qp","to return to smw"
"to go up smw","salire qp","to go up smw"
"to prefer sth","preferire qc","to prefer sth"
"to prefer doing sth","preferire fare qc","to prefer doing sth"
"to die from sth","morire di qc","to die from sth"
"to wait for sb/sth","aspettare qn/qc","to wait for sb/sth"
"to buy sth for sb","comprare qc a qn","to buy sth for sb"
"to be born smw","nascere qp","to be born smw"
"to search for sth","cercare qc","to search for sth"
"to try to do sth","cercare di fare qc","to try to do sth"
"to lose sth","perdere qc","to lose sth"
"to sing sth","cantare qc","to sing sth"
"to sing to sb","cantare a qn","to sing to sb"
"to pass sth","passare qc","to pass sth"
"to start sth","cominciare qc","to start sth"
"to start doing sth","cominciare a fare qc","to start doing sth"
"to listen to sth","ascoltare qc","to listen to sth"
"to succeed in sth","riuscire in qc","to succeed in sth"
"to manage, be able to do sth","riuscire in qc","to manage, be able to do sth"
"to succeed in doing sth","riuscire a fare qc","to succeed in doing sth"
"to decide sth","decidere qc","to decide sth"
"to decide to do sth","decidere di fare qc","to decide to do sth"
"to live smw","abitare a/in qp","to live smw"
"to fall smw","cadere qp","to fall smw"
"to close sth","chiudere qc","to close sth"
"to leave smw","lasciare qp","to leave smw"
"to leave sb sth, sth to sb","lasciare qc a qn","to leave sb sth, sth to sb"
"to choose sth","scegliere qc","to choose sth"
"to choose to do sth","scegliere di fare qc","to choose to do sth"
"to carry sth","portare qc","to carry sth"
"to take/bring sth to sb","portare qc a qn","to take/bring sth to sb"
"to receive sth","ricevere qc","to receive sth"
"to wash sth","lavare qc","to wash sth"
"to answer sb","rispondere a qn","to answer sb"
"to sit smw","sedere qp","to sit smw"
"to win sth","vincere qc","to win sth"
"to pay sth","pagare qc","to pay sth"
"to raise/lift sth","alzare qc","to raise/lift sth"
"to laugh at sth","ridere di qc","to laugh at sth"
"to go down smw","scendere qp","to go down smw"
"to get down/off of sth","scendere da qc","to get down/off of sth"
"to encounter/meet sb","incontrare qn","to encounter/meet sb"
"to offer sth","offrire qc","to offer sth"
"to offer sth to sb, sb sth","offrire qc a qn","to offer sth to sb, sb sth"
"to learn sth","imparare qc","to learn sth"
"to learn to do sth","imparare a fare qc","to learn to do sth"
"to forget sth","dimenticare qc","to forget sth"
"to forget to do sth","dimenticare di fare qc","to forget to do sth"
"to wake sb up","svegliare qn","to wake sb up"
"to grow up smw","crescere qp","to grow up smw"
"to grow sth","crescere qc","to grow sth"
"to sell sth","vendere qc","to sell sth"
"to sell sth to sb, sb sth","vendere qc a qn","to sell sth to sb, sb sth"
"to have fun with sb","divertirsi con qn","to have fun with sb"
"to have fun doing sth","divertirsi a fare qc","to have fun doing sth"
"to become sth","diventare qc","to become sth"
"to place/put sth smw","mettere qc qp","to place/put sth smw"
"to enter smw","entrare in qp","to enter smw"
"to fear sth","temere qc","to fear sth"
"to clean sth","pulire qc","to clean sth"
"to dress in sth","vestire di qc","to dress in sth"
"to follow sb","seguire qn","to follow sb"
"to stay/remain smw","restare qp","to stay/remain smw"
"to change sth","cambiare qc","to change sth"
"to travel to smw","viaggiare a qp","to travel to smw"
"to turn off sth","spegnere qc","to turn off sth"
"to remember sth","ricordare qc","to remember sth"
"to remember to do sth","ricordare di fare qc","to remember to do sth"
"to remember having done, doing sth","ricordare di aver fatto qc","to remember having done, doing sth"
"to appear smw","apparire qp","to appear smw"
"to help sb","aiutare qn","to help sb"
"to help sb to do sth","aiutare qn a fare qc","to help sb to do sth"
"to be quiet about sth","tacere su qc","to be quiet about sth"
"to send/ship sth","spedire qc","to send/ship sth"
"to send/ship sth to sb, sb sth","spedire qc a qn","to send/ship sth to sb, sb sth"
"to prepare sth","preparare qc","to prepare sth"
